Send auth mode telemetry events
AzureAD/microsoft-authentication-cli pull request #103
Opened 2022-06-10 23:31 UTC by mvanchaa

2022-06-13 19:06 UTC, goagain requested changes

2022-06-13 19:06 UTC, goagain commented on src/AzureAuth/Program.cs
> +            string applicationInsightsIngestionToken = "2ba47d2c-65c4-4bf9-a77a-f8ffd05cbafe";
Is this an internal token? If yes, delete this branch as soon as possible. It's too dangerous.

2022-06-13 22:52 UTC, shalinikhare27 commented
@mvanchaa - I would first break this PR into multiple PRs for easy review. :)

2022-06-13 22:53 UTC, shalinikhare27 commented
Also, side note, I am implementing IWA as a auth flow. So depending on who's PR gets merged first, one of us will need to add telemetry in IWA as well. :)

2022-06-14 01:02 UTC, mvanchaa commented
> Also, side note, I am implementing IWA as a auth flow. So depending on who's PR gets merged first, one of us will need to add telemetry in IWA as well. :)

@shalinikhare27 Yup, I was planning to add those changes to IWA after yours is merged.

2022-06-14 01:36 UTC, mvanchaa commented
> @mvanchaa - I would first break this PR into multiple PRs for easy review. :)

Thanks for the suggestion @shalinikhare27! That will make things easy for me too :)

2022-06-14 18:53 UTC, closed without merging