Adding section for setting custom timeout in usage docs
AzureAD/microsoft-authentication-cli pull request #149
Opened 2022-09-14 20:01 UTC by Haard30

Recently, we received [feedback](https://office.visualstudio.com/OE/_workitems/edit/5851307#22462190) to add the information about default timeout and it's usage in our docs.

This PR contains adding a section in `docs/usage` for setting custom timeout.

2022-09-14 20:10 UTC, kyle-rader requested changes
I have a small wording suggestion and otherwise looks good. Thanks for adding!

2022-09-14 20:10 UTC, kyle-rader commented on docs/usage.md
> +Azureauth currently defaults to 15 minutes timeout. You can also set your custom timeout in minutes which can be a decimal number.
```suggestion
Azureauth defaults to a 15 minute timeout. You can override this with a custom timeout value using `--timeout`. The value is interpreted as a decimal number of minutes. The example below will wait 10 minutes and 45 seconds.
```

2022-09-14 20:35 UTC, reillysiemens approved these changes

2022-09-14 20:42 UTC, melindajohnson approved these changes

2022-09-16 23:54 UTC, kyle-rader approved these changes

2022-09-16 23:55 UTC, merged