Handling invalid AZUREAUTH_CONFIG
AzureAD/microsoft-authentication-cli pull request #162
Opened 2022-10-24 20:13 UTC by Haard30

If an invalid configuration file is specified via the `AZUREAUTH_CONFIG` environment variable, then the user is given a stack trace. In contrast, if the `--config` flag is used then the user gets a proper message which says "The file '<filename>.toml' does not exist.". This is because the config flag is checked and the error is handled with [FileExists] options check, while if we use `AZUREAUTH_CONFIG` environment variable, we have to specifically catch that error.

Adding a catch statement to make sure we catch `FileNotFound` exception and provide similar experience.

Also added a test case to verify the code works as expected.

2022-10-24 20:50 UTC, reillysiemens submitted a review, later dismissed

2022-10-24 20:50 UTC, goagain approved these changes

2022-10-25 18:24 UTC, goagain requested changes

2022-10-25 18:28 UTC, mvanchaa submitted a review, later dismissed

2022-10-25 19:43 UTC, kyle-rader commented on src/AzureAuth.Test/CommandMainTest.cs
> +            this.envMock.Verify();
```suggestion
            this.envMock.VerifyAll();

```

2022-10-25 19:48 UTC, kyle-rader requested changes
1 suggestion to use VerifyAll instead of Verify. This way any future additions do not require adding more calls to Verify. (I'm only 60% sure on this, I don't recall the exact behave differences, only that Verify is typically what you want to setup a custom verification on the mock, while VerifyAll ensures all things that were mocked, were called, and nothing un-mocked was called.

2022-10-25 21:09 UTC, kyle-rader approved these changes

2022-10-25 21:11 UTC, goagain approved these changes

2022-10-25 21:11 UTC, merged