Update changelog and readme for 0.5.5 release
AzureAD/microsoft-authentication-cli pull request #163
Opened 2022-10-25 21:25 UTC by Haard30

Update changelog so that it references to 0.5.5
Update README to default to 0.5.5 for example release.

2022-10-25 21:35 UTC, melindajohnson approved these changes

2022-10-25 22:30 UTC, kyle-rader requested changes

2022-10-25 22:30 UTC, kyle-rader commented on CHANGELOG.md
> +## [0.5.5] - 2022-10-25
@Haard30 I think the change to output utf-8 warrents we move to 0.6.0 because it is a breaking change for some users.

2022-10-25 22:37 UTC, melindajohnson submitted a review, later dismissed

2022-10-26 07:07 UTC, kyle-rader approved these changes

2022-10-26 16:03 UTC, reillysiemens commented
@Haard30: Normally I don't recommend this, but in this case I think you can cleanly squash these commits into a single commit for `0.6.0`.

2022-10-26 16:34 UTC, goagain approved these changes

2022-10-26 20:38 UTC, melindajohnson submitted a review, later dismissed

2022-10-26 20:47 UTC, goagain approved these changes

2022-10-26 20:48 UTC, mvanchaa submitted a review, later dismissed

2022-10-26 21:31 UTC, reillysiemens approved these changes

2022-10-26 21:45 UTC, goagain approved these changes

2022-10-26 21:46 UTC, mvanchaa approved these changes

2022-10-26 21:50 UTC, merged