Add Debian installation scripts and update workflow to release Linux binaries
AzureAD/microsoft-authentication-cli pull request #188
Opened 2023-01-30 17:46 UTC by mvanchaa

2023-01-31 19:36 UTC, reillysiemens requested changes
I made some minuscule requests for changes here. Overall this looks good. However, I think we should wait to merge this until we know we can actually publish the `.deb` package.

2023-01-31 19:36 UTC, reillysiemens commented on .github/workflows/release.yml
> +      run: python .\bin\trigger_azure_pipelines.py
These are backslashes and I think you're gonna find that gets weird (probably doesn't work as you expect) on Linux. Try `/` instead.

2023-01-31 19:36 UTC, reillysiemens commented on README.md
> +
I think this extra newline is probably not necessary.

2023-01-31 19:39 UTC, mvanchaa commented
> I made some minuscule requests for changes here. Overall this looks good. However, I think we should wait to merge this until we know we can actually publish the `.deb` package.

I agree with you. Thanks for reviewing @reillysiemens

2023-02-23 00:40 UTC, mvanchaa commented
Closed this by mistake.

2023-03-02 20:08 UTC, closed without merging