Create functional `TokenFetcher` orchestrator for AAD and Azure Devops
AzureAD/microsoft-authentication-cli pull request #214
Opened 2023-03-01 22:43 UTC by kyle-rader-msft

# What are we adding?
This PR reincarnates `TokenFetcher` but this time as a focussed, [functional](https://en.wikipedia.org/wiki/Functional_programming), abstraction around creating auth flows, an authflow executor, and applying our locking logic around doing the auth process with all those parameters.

You may notice some long argument lists. A Data Clump is emerging, but I don't think it's worth trying to address it at this time until we have more need to. Early abstractions of data clump easily lead to wrong abstractions.

# What are we not adding?
Notice, this PR is purely additive for `TokenFetcher`s and The only changes to existing code are to the unflighted/unsed PatFromEnv class, which is now more aptly named. 

# Inspiration from Elixir and Rust

The abstraction for TokenFetcher's here _could_ use objects. But we don't really _need_ to so we've taken a functional approach.

## Results
To return more meaningly data types I've renamed both sub records of `PatFromEnv` and `TokenFetcher` to have a `Result` type. Something we can always return and ensure is not null, and represent the outcome of token fetching, mostly without null. These are declared _inside_ their respective static classes because they are intimately coupled, intentionally.

2023-03-01 22:44 UTC, kyle-rader-msft commented on src/AzureAuth/Ado/PatFromEnv.cs
> +        public record Result
This is renamed and moved from below. Nothing actually new here.

2023-03-02 22:24 UTC, kyle-rader-msft commented on src/MSALWrapper/TokenFetcher.cs
> +            var authFlows = AuthFlowFactory.Create(
This method is almost copied directly from `CommandAad.GetToken` with 1 important change - there's not yet a way to inject an IAuthFlow. We are tightly coupled with the AuthFlowFactory.

There is only 1 test requireing that and it's sort of an integration level test as all the components used here, aside from the lock, are unit tested already. I'm still pondering if we will want to add this ability. I'm leaning yes - and will do that when required to do by updating the CommandAad usage.

2023-03-02 22:29 UTC, reillysiemens requested changes

2023-03-02 22:29 UTC, reillysiemens commented on src/MSALWrapper/TokenFetcher.cs
> +        /// <param name="timeout">Timeout.</param>
Same here. Real descriptions, please.

2023-03-02 22:29 UTC, reillysiemens commented on src/MSALWrapper/TokenFetcher.cs
> +        public static async Task<Result> AccessTokenAsync(ILogger logger, Guid client, Guid tenant, IEnumerable<string> scopes, AuthMode mode, string domain, string prompt, TimeSpan timeout)
```suggestion
        public static async Task<Result> AccessTokenAsync(
            ILogger logger,
            Guid client,
            Guid tenant,
            IEnumerable<string> scopes,
            AuthMode mode,
            string domain,
            string prompt,
            TimeSpan timeout)
```

2023-03-02 22:29 UTC, reillysiemens commented on src/MSALWrapper/TokenFetcher.cs
> +            List<AuthFlowResult> results = new List<AuthFlowResult>();
```suggestion
            List<AuthFlowResult> results = new List<AuthFlowResult>();
            var executor = new AuthFlowExecutor(logger, authFlows, new StopwatchTracker(timeout));
```

2023-03-02 22:29 UTC, reillysiemens commented on src/MSALWrapper/TokenFetcher.cs
> +            // It should be false otherwise a dead lock could occur.
```suggestion
            // It should be false otherwise a deadlock could occur.

```

2023-03-02 22:48 UTC, goagain approved these changes

2023-03-02 22:48 UTC, goagain commented on src/AzureAuth/Ado/TokenFetcher.cs
> +        /// Get an Azure Devops AAD access token.
nit
```suggestion
        /// Get an Azure DevOps AAD access token.
```

2023-03-02 22:48 UTC, goagain commented on src/AzureAuth/Ado/TokenFetcher.cs
> +                scopes: new[] { Constants.Scope.AzureDevopsDefault },
Is DevOps better than Devops?
```suggestion
                scopes: new[] { Constants.Scope.AzureDevOpsDefault },
```

2023-03-02 22:48 UTC, reillysiemens submitted a review, later dismissed

2023-03-02 22:57 UTC, reillysiemens approved these changes

2023-03-02 22:57 UTC, goagain approved these changes

2023-03-03 01:21 UTC, reillysiemens commented on src/MSALWrapper/TokenFetcher.cs
> +                    lockAcquired = mutex.WaitOne(TimeSpan.FromMinutes(15)); // TODO: Inject mutex timeout?
@shalinikhare27 mentioned in #218 that we can remove the `TODO` comment here and the timespan can become `const`.

2023-03-03 01:38 UTC, reillysiemens approved these changes

2023-03-03 01:44 UTC, reillysiemens approved these changes

2023-03-03 05:30 UTC, shalinikhare27 approved these changes

2023-03-03 17:20 UTC, merged