ado token command: add default value for --domain of microsoft
AzureAD/microsoft-authentication-cli pull request #276
Opened 2023-04-19 23:25 UTC by Haard30

Adding the default `@microsoft.com` domain for `ado token` command.

2023-04-19 23:37 UTC, goagain submitted a review, later dismissed

2023-04-19 23:42 UTC, kyle-rader-msft requested changes

2023-04-19 23:42 UTC, kyle-rader-msft commented on src/AzureAuth/Commands/Ado/CommandToken.cs
> +        private string Domain { get; set; } = AzureAuth.Ado.Constants.PreferredDomain;
Can we change the Domain help text to match the CommandAdoPat help text? That help indicates the default on the ADO command is Microsoft, while the generic Aad command does not (and has no default)

2023-04-19 23:49 UTC, reillysiemens reviewed
Setting a default for this seems worthy of a `CHANGELOG.md` update.

2023-04-20 06:41 UTC, kyle-rader-msft requested changes

2023-04-20 06:41 UTC, kyle-rader-msft commented on CHANGELOG.md
> +- The `azureauth ado token` command now defaults to `microsoft.com` domain.
```suggestion
- The `azureauth ado token` command uses `microsoft.com` as the default `--domain` option value.
```

2023-04-20 18:03 UTC, reillysiemens approved these changes

2023-04-20 18:41 UTC, kyle-rader-msft approved these changes

2023-04-20 18:43 UTC, merged