Enable Linux release from ADO.
AzureAD/microsoft-authentication-cli pull request #315
Opened 2023-07-19 22:34 UTC by goagain

This PR contains 2 changes.
- Enable building Linux packages from ADO pipelines again. It will generate both `amd64` and `arm64` packages.
- The ADO pipeline is staged not. We don't need to wait for the publish stage. After the `Sign` stage completed, We can download the artifacts.

2023-08-02 00:29 UTC, goagain commented
@AzureAD/security-experience The pipeline has been validated. Please have a review.

2023-08-03 19:12 UTC, mvanchaa requested changes

2023-08-03 19:12 UTC, mvanchaa commented on bin/trigger_azure_pipelines.py
>  # https://learn.microsoft.com/en-us/rest/api/azure/devops/pipelines/runs/get?view=azure-devops-rest-6.0#runresult
@goagain can you update the comment here with the right reference link?

2023-08-03 19:12 UTC, mvanchaa commented on bin/trigger_azure_pipelines.py
> +FAILED_STATUSES: set[str] = {"canceled", "failed", "skipped", "unknown"}
There is another status called `abandoned`. And `unknown` status doesn't exist. https://learn.microsoft.com/en-us/rest/api/azure/devops/build/timeline/get?view=azure-devops-rest-6.0#taskresult. I think we should handle that scenario as well.

2023-08-03 21:42 UTC, mvanchaa submitted a review, later dismissed

2023-08-04 19:04 UTC, reillysiemens commented on bin/trigger_azure_pipelines.py
> +        record = next(filter(lambda record: record.identifier == stage_id, records), None)
```suggestion
        record = next((r for r in records if r.identifier == stage_id), None)
```

2023-08-04 19:05 UTC, reillysiemens commented on bin/trigger_azure_pipelines.py
> +        records = timeline.records
If you take my suggestion below you don't need this line.

2023-08-04 19:09 UTC, reillysiemens submitted a review, later dismissed

2023-08-04 19:10 UTC, goagain commented on bin/trigger_azure_pipelines.py
> +        records = timeline.records
```suggestion
```

2023-08-04 19:28 UTC, mvanchaa approved these changes

2023-08-04 19:33 UTC, reillysiemens approved these changes

2023-08-04 19:43 UTC, merged