XML comment clean up in MSALWrapper and MSALWrapperTest
AzureAD/microsoft-authentication-cli pull request #53
Opened 2022-05-02 16:39 UTC by melindajohnson

Cleaning up the XML comments in MSALWrapper and removing XML comments in MSALWrapper Test.

2022-05-02 18:35 UTC, shalinikhare27 commented on src/MSALWrapper/AuthMode.cs
> +        /// <summary>/// The web./// </summary>
We want the summary to be more meaningful than "The web". These were added by me using resharper which does a poor job of creating meaingful summaries but adds a placeholder.

2022-05-02 18:36 UTC, shalinikhare27 commented on src/MSALWrapper/ExceptionExtensions.cs
>      /// The get all exceptions.
Definitely needs an update. ;)

2022-05-02 18:41 UTC, shalinikhare27 commented
Sorry I didn't see this is in draft. I will wait for it to go live. The summaries can be improved to more meaningful content.

2022-05-11 18:50 UTC, goagain commented on src/MSALWrapper/JsonWebTokenExtensions.cs
> +    /// json web token extensions.
```suggestion
    /// Json web token extensions.

```

2022-05-11 19:08 UTC, goagain requested changes

2022-05-11 19:08 UTC, goagain commented on src/MSALWrapper/ITokenFetcher.cs
> +        /// <returns>/// The <see cref="Task"/>.</returns>
```suggestion
        /// <returns>The <see cref="Task"/>.</returns>
```

2022-05-11 19:08 UTC, goagain commented on src/MSALWrapper/ITokenFetcher.cs
> +        /// <returns>/// The <see cref="Task"/>.
```suggestion
        /// <returns>
        /// The <see cref="Task"/>.
```

2022-05-11 19:08 UTC, goagain commented on src/MSALWrapper/ITokenFetcher.cs
> +        /// <param name="authMode">/// The auth mode.</param>
```suggestion
        /// <param name="scopes">The scopes.</param>
        /// <param name="authMode">The auth mode.</param>
```

2022-05-11 19:08 UTC, goagain commented on src/MSALWrapper/ITokenFetcher.cs
> +        /// <param name="authMode">/// The auth mode.</param>
```suggestion
        /// <param name="authMode">The auth mode.</param>
```

2022-05-11 19:08 UTC, goagain commented on src/MSALWrapper/ITokenFetcher.cs
> +        /// <returns>/// The <see cref="Task"/>.</returns>
```suggestion
        /// <param name="scopes">The scopes.</param>
        /// <returns>The <see cref="Task"/>.</returns>
```

2022-05-11 19:08 UTC, goagain commented on src/MSALWrapper/ITokenFetcher.cs
> +        /// <returns>/// The <see cref="Task"/>.</returns>
```suggestion
        /// <returns>The <see cref="Task"/>.</returns>
```

2022-05-11 20:35 UTC, goagain requested changes
You can use `Add to batch` in tab `File Changed` to combine them into one commit.

2022-05-11 20:35 UTC, goagain commented on src/MSALWrapper/AuthMode.cs
> +        /// <returns>/// The <see cref="bool"/>.</returns>
```suggestion
        /// <param name="authMode">The auth mode.</param>
        /// <returns>The <see cref="bool"/>.</returns>
```

2022-05-11 20:35 UTC, goagain commented on src/MSALWrapper/AuthMode.cs
> +        /// <returns>/// The <see cref="bool"/>.</returns>
```suggestion
        /// <param name="authMode">The auth mode.</param>
        /// <returns>The <see cref="bool"/>.</returns>
```

2022-05-11 20:35 UTC, goagain commented on src/MSALWrapper/AuthenticationTimeoutException.cs
> +        /// <param name="message">/// The message.</param>
```suggestion
        /// <param name="message">The message.</param>
```

2022-05-11 20:35 UTC, goagain commented on src/MSALWrapper/ExceptionListToStringConverter.cs
> +        /// <param name="exceptions">/// The exceptions.</param>
```suggestion
        /// <param name="exceptions">The exceptions.</param>
```

2022-05-11 23:46 UTC, kyle-rader submitted a review, later dismissed

2022-05-12 23:28 UTC, mvanchaa approved these changes

2022-05-13 20:59 UTC, reillysiemens commented
To answer your question, @goagain, I tend to write these things as imperatives, so I'd write something like
```
Get a display name.
```
I agree that we should be consistent here.

2022-05-13 21:07 UTC, reillysiemens approved these changes

2022-05-13 21:19 UTC, reillysiemens approved these changes

2022-05-13 21:33 UTC, mvanchaa approved these changes

2022-05-13 21:34 UTC, goagain approved these changes

2022-05-13 21:34 UTC, merged